# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manual trigger Maven release build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: '1.0.0'
      next_version:
        description: 'Next SNAPSHOT version'
        required: true
        default: '1.0.1-SNAPSHOT'

jobs:
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Prepare and release
        run: mvn -Dresume=false -DreleaseVersion=${github.event.inputs.release_version} -DdevelopmentVersion=${github.event.inputs.next_version} -DdeployAtEnd=true -Dgoals=deploy release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}